<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="notation"
    nsURI="http://www.eclipse.org/gmf/runtime/1.0.0/notation" nsPrefix="notation">
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//View">
    <eOperations name="createBendpoints" eType="#//Bendpoints">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="createSourceAnchor" eType="#//Anchor">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="createTargetAnchor" eType="#//Anchor">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//View" resolveProxies="false" eOpposite="#//View/sourceEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//View" resolveProxies="false" eOpposite="#//View/targetEdges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" eType="#//Bendpoints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAnchor" eType="#//Anchor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetAnchor" eType="#//Anchor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//View">
    <eOperations name="createLayoutConstraint" eType="#//LayoutConstraint">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutConstraint" eType="#//LayoutConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FillStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="16777215"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="11579568"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FontStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Tahoma"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="9"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="underline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strikeThrough" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TitleStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortingStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sorting" eType="#//Sorting"
        defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortingKeys" eType="#//SortKeyMap"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sortedObjects" upperBound="-1"
        eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptionStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutConstraint" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Size" eSuperTypes="#//LayoutConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//LayoutConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bounds" eSuperTypes="#//Location #//Size"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ratio" eSuperTypes="#//LayoutConstraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Anchor" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bendpoints" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Sorting">
    <eLiterals name="None"/>
    <eLiterals name="Manual" value="1"/>
    <eLiterals name="Automatic" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Filtering">
    <eLiterals name="None"/>
    <eLiterals name="Manual" value="1"/>
    <eLiterals name="Automatic" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentityAnchor" eSuperTypes="#//Anchor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="anchor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Routing">
    <eLiterals name="Manual"/>
    <eLiterals name="Rectilinear" value="1"/>
    <eLiterals name="Tree" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Smoothness">
    <eLiterals name="None"/>
    <eLiterals name="Normal" value="1"/>
    <eLiterals name="Less" value="2"/>
    <eLiterals name="More" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JumpLinkStatus">
    <eLiterals name="None"/>
    <eLiterals name="All" value="1"/>
    <eLiterals name="Below" value="2"/>
    <eLiterals name="Above" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JumpLinkType">
    <eLiterals name="Semicircle"/>
    <eLiterals name="Square" value="1"/>
    <eLiterals name="Chamfered" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routing" eType="#//Routing"
        defaultValueLiteral="Manual"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="smoothness" eType="#//Smoothness"
        defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avoidObstructions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="closestDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpLinkStatus" eType="#//JumpLinkStatus"
        defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpLinkType" eType="#//JumpLinkType"
        defaultValueLiteral="Semicircle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jumpLinksReverse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" abstract="true" eSuperTypes="../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement">
    <eOperations name="getStyle" eType="#//Style">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="createChild" eType="#//Node">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="createStyle" eType="#//Style">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mutable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEdges" upperBound="-1"
        eType="#//Edge" resolveProxies="false" eOpposite="#//Edge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEdges" upperBound="-1"
        eType="#//Edge" resolveProxies="false" eOpposite="#//Edge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistedChildren" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="styles" upperBound="-1"
        eType="#//Style" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//Diagram" changeable="false" volatile="true" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transientChildren" upperBound="-1"
        eType="#//Node" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeBendpoints" eSuperTypes="#//Bendpoints">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="#//RelativeBendpointList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram" eSuperTypes="#//View">
    <eOperations name="createEdge" eType="#//Edge">
      <eParameters name="eClass" eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistedEdges" upperBound="-1"
        eType="#//Edge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TransientEdges" upperBound="-1"
        eType="#//Edge" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Image">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CanonicalStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canonical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShapeStyle" eSuperTypes="../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject #//FontStyle #//DescriptionStyle #//FillStyle #//LineStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectorStyle" eSuperTypes="../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject #//RoutingStyle #//LineStyle"/>
  <eClassifiers xsi:type="ecore:EDataType" name="RelativeBendpointList" instanceClassName="java.util.List"/>
  <eClassifiers xsi:type="ecore:EClass" name="PageStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageHeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawerStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collapsed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuideStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EReference" name="horizontalGuides" upperBound="-1"
        eType="#//Guide" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verticalGuides" upperBound="-1"
        eType="#//Guide" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Guide">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeMap" upperBound="-1"
        eType="#//NodeEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//Alignment"
        defaultValueLiteral="Center"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Alignment">
    <eLiterals name="Left"/>
    <eLiterals name="Right" value="1"/>
    <eLiterals name="Center" value="2"/>
    <eLiterals name="Top" value="3"/>
    <eLiterals name="Bottom" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilteringStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filtering" eType="#//Filtering"
        defaultValueLiteral="None"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filteringKeys" eType="#//FilterKeyList"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filteredObjects" upperBound="-1"
        eType="ecore:EClass ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FilterKeyList" instanceClassName="java.util.List"/>
  <eClassifiers xsi:type="ecore:EDataType" name="SortKeyMap" instanceClassName="java.util.Map"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SortingDirection">
    <eLiterals name="Ascending"/>
    <eLiterals name="Descending" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramStyle" eSuperTypes="../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject #//PageStyle #//GuideStyle #//DescriptionStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImageStyle" eSuperTypes="#//Style">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antiAlias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maintainAspectRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cropBound" lowerBound="1"
        eType="#//Bounds" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageBufferStyle" eSuperTypes="#//ImageStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imageBuffer" lowerBound="1"
        eType="#//Image" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
