/**
 * <copyright>
 * </copyright>
 *
 * $Id: RoutingStyleValidator.java,v 1.1 2007/05/17 16:26:49 aboyko Exp $
 */
package org.eclipse.gmf.runtime.notation.validation;

import org.eclipse.gmf.runtime.notation.JumpLinkStatus;
import org.eclipse.gmf.runtime.notation.JumpLinkType;
import org.eclipse.gmf.runtime.notation.Routing;
import org.eclipse.gmf.runtime.notation.Smoothness;

/**
 * A sample validator interface for {@link org.eclipse.gmf.runtime.notation.RoutingStyle}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RoutingStyleValidator {
	boolean validate();

	boolean validateRouting(Routing value);
	boolean validateSmoothness(Smoothness value);
	boolean validateAvoidObstructions(boolean value);
	boolean validateClosestDistance(boolean value);
	boolean validateJumpLinkStatus(JumpLinkStatus value);
	boolean validateJumpLinkType(JumpLinkType value);
	boolean validateJumpLinksReverse(boolean value);
}
