/**
 * <copyright>
 * </copyright>
 *
 * $Id: StringToPropertyValueMapEntryValidator.java,v 1.1 2007/05/17 16:26:49 aboyko Exp $
 */
package org.eclipse.gmf.runtime.notation.validation;

import org.eclipse.gmf.runtime.notation.PropertyValue;

/**
 * A sample validator interface for {@link java.util.Map.Entry}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StringToPropertyValueMapEntryValidator {
	boolean validate();

	boolean validateTypedKey(String value);
	boolean validateTypedValue(PropertyValue value);
}
