/**
 * <copyright>
 * </copyright>
 *
 * $Id: ViewValidator.java,v 1.1 2007/05/17 16:26:49 aboyko Exp $
 */
package org.eclipse.gmf.runtime.notation.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.gmf.runtime.notation.Diagram;

/**
 * A sample validator interface for {@link org.eclipse.gmf.runtime.notation.View}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ViewValidator {
	boolean validate();

	boolean validateVisible(boolean value);
	boolean validateType(String value);
	boolean validateMutable(boolean value);
	boolean validateSourceEdges(EList value);
	boolean validateTargetEdges(EList value);
	boolean validatePersistedChildren(EList value);
	boolean validateStyles(EList value);
	boolean validateElement(EObject value);
	boolean validateDiagram(Diagram value);
	boolean validateTransientChildren(EList value);
}
